#!/usr/local/bin/Rscript
#' COVID-19 rolling mean of daily percent change in deaths for all states.
#'
#' Report a rolling mean (currently 5-day) of the percent change in
#' deaths for all or a set of states.
#'
#' This program uses the per state csv files generated by
#' cov_state_ts.R.  I should just turn this into a function that can
#' be used within this program. But, for now, I generate the files
#' manually with
#' perl -ane '`~/bin/cov_state_ts.R $_`; print $_' ~/data/state.short
#'
#' usage: cov_all_states_ts_chg.R
#' 

rm(list=ls())
suppressMessages(library(data.table))
suppressMessages(library(lubridate))
options(width=200)

kInputFile <- "states"
kInputDir <- "~/data"
kDataDir <- "~/data/cova"
kOutputDir <- kInputDir
kOutputFile <- 'all_states.csv'
kOutputXtFile <- "cov_all_states_ts_chg.csv"

inPath <- file.path(kInputDir, kInputFile)

statedf <- read.table(inPath, header=F)
names(statedf) = c("name")
statedf$name = gsub(' ','_',statedf$name)
combdt = data.table()
for (s in statedf$name) {
    inPath = file.path(kDataDir, paste0(s,".csv"))
    cat(inPath,"\n")
    dt = fread(inPath)
    combdt = rbind(combdt, dt)
}
combdt$report_date = as.Date(combdt$report_date)
outPath = file.path(kOutputDir, kOutputFile)
write.csv(combdt, file=outPath, row.names=F, quote=F)
cat(nrow(combdt), "rows saved in", outPath,"\n")
## combdt[date==last(date),.(state,dDeltaPctRollMean5d)][order(dDeltaPctRollMean5d)]

endPeriod = last(combdt$report_date)
startPeriod = endPeriod - 5
xt <- xtabs(dDeltaPctRollMean5d ~ state+report_date, data=combdt[report_date > startPeriod])
xt
write.csv(xt, file=kOutputXtFile)
cat("saved in", kOutputXtFile, "\n")
